# -*- coding: utf-8 -*-
"""PID project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyNqxvRhJafusqKeh8Hg0YM_n1NLMGi6
"""

!pip install easyocr

import matplotlib.pyplot as plt
import cv2
import easyocr
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize']=8, 16

reader=easyocr.Reader(['en'])

Image("/content/PID.png")

output=reader.readtext("/content/PID.png")

output

import pandas as pd

cord=output[-1][0]

cord

df=pd.DataFrame(output)

df[1]

df[1].to_excel("index.xlsx")



